### PR TITLE
Rename parsePolicies to parseSwaggerPolicies to avoid conflict

### PR DESCRIPTION
**Pull request by jiangpengcheng**
resolve: #376

### CODE REVIEW

**Comment by mhamann** [comment]
@jiangpengcheng the CI is failing. I suspect you didn't update some tests. Can you take a look?

**Comment by jiangpengcheng** [comment]
seems that travis build will use `openwhisk/apigateway:nightly` while it doesn't tag locally built apigateway image with `nightly` tag?

**Comment by jiangpengcheng** [comment]
@mhamann although this PR resolve the conflict problem. but I'm not clear why this conflict happens. I know nothing about the lua language, do you have any idea? thanks

**Comment by style95** [comment]
I merged this as many dependent tests are failing in the core repo.

**Pull request merged**
